version: "3"

services:
  backend:
    build: ./backend
    environment:
      - DJANGO_DEBUG=true
      - PROJECT=EIA003
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/backend
      - ~/.aws:/root/.aws
    command: sls wsgi serve --host 0.0.0.0

  frontend:
    build: ./frontend
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:5000
      - REACT_APP_FRONTEND_URL=http://localhost:3000
      - PARAMETER_PATH=/dev/EIA003
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/frontend
      - ~/.aws:/root/.aws
    depends_on:
      - backend
    entrypoint: ["sh", "/frontend/entrypoint.sh"]
